### ISSUE TITLE
Vimeo Lazy Load not working

### ISSUE THREAD

**Issue by lucasdidthis** [kevinweber/lazy-load-for-videos#22]
Hejhej!

Thanks for your good work, but I have to annoy you with another issue. :-(

The Vimeo-Video-Embed does not work as supposed: The Video embed loads stuff (cookies, a script and a/the frame) from vimeo right when the website is loaded _- and not after I click on the playbutton/screenshot._ Thats exactly what I want to prevent with your plugin.

I'm running WordPress 5.2 with the basic "Twenty Nineteen" theme and your Plugin in Version 2.7.1.

Thanks in advance,
All the best

Lucas

**Comment by lucasdidthis** [comment]
I'm not sure why, though, because I can't see the frame in the code before the playbutton/screenshot is pushed.

And there's another Vimeo-Issue: When the video is not 16:9, the screenshot is not sized correctly.

**Comment by kevinweber** [comment]
1. Have you checked the "Responsive Mode" option in the admin panel?

2. On my test site, I'm not seeing the Vimeo player JS. Can you please provide more details about what scripts are being loaded and share a link to a page where I can see it in action?

On my test site, if the plugin is NOT enabled, the following script is loaded:
https://f.vimeocdn.com/p/3.11.17/js/player.js

If the plugin IS enabled and videos are lazy loaded, the page is still making requests to Vimeo in order to get the thumbnail. However, the player script is NOT called. Those are the two Vimeo-related requests I'm seeing with the plugin enabled:
https://vimeo.com/api/v2/video/82540173.json.json?callback=showThumb
https://i.vimeocdn.com/video/458979555_640.jpg

Also make sure that you don't have other plugins or widgets (e.g. in the footer) that might be requesting a Vimeo video.

**Comment by lucasdidthis** [comment]
You're right, the Script that is called, is coming from "https://vimeo.com/api/v2/video/316593453.json.json?callback=showThumb". I guess it is caused when the video grabs the screenshot, but the YouTube-Videos aren't doing anything similiar, so I guess this must not be?
 
The problem with this call is, if any sort of third-party-script-blocking is active, the vimeo screenshot is not loaded at all, because it needs the script to work. I've attached a screenshot of the stuff, the uMatrix logging detects when calling the website. Be aware that the Youtube video only causes a single image request, but the Vimeo video loads a tone of stuff just for the screenshot:

![vimeo_tracking](https://user-images.githubusercontent.com/7188739/57971632-c5112f00-7990-11e9-9a7b-c2b9e5e029c1.jpg)

Regarding the correct sizing of the screnshots: 
If I do not activate the **Responsive Mode**, the screenshots are to small, if I do activate it, everything is fine for 16:9 videos, but wrong for anything else. Am I supposed to check it or not?

You can take a look yourself at both problems on inkmyday.com (user: admin, pw.: ww2019). You'll notice the styling problem mentioned in Issue #23 , too. I've stripped down the theme, to eliminate possible issue sources, so it looks a little funky..

**Comment by kevinweber** [comment]
Thanks, your insights are really helpful.

Regarding the API call: Unfortunately, Vimeo requires a call to their API in order to retrieve the thumbnail. This is different from Youtube where it's possible to get a useful thumbnail simply by inserting the ID of a video into an image URL.
You could change the "Thumbnails/Patterns" option in the admin panel to display one of the predefined patterns or no thumbnail at all. That way no thumbnails will be requested at all. This setting will affect Youtube thumbnails as well.

Regarding the responsive mode: I can see what you see as an issue. However, it's working as I expect it to work currently. It would be possible to implement a per-video responsive sizing feature by supporting some custom query param that you could append to each video URL.
I don't plan on implementing this feature, though. I want to keep the plugin simple. Plus, there might be users who actually prefer to have thumbnails with a consistent size even if the ratio of individual iframes.

**Comment by lucasdidthis** [comment]
Thank you very much for the info.

I still wish there would be an option for "real" responsive sizing, though. Couldn't it be an option to implement the feature by supporting some kind of classes for the embed video element? Like giving those video blocks the class "ratio_x-y" (ratio_16-9, ratio_4-3, etc.) for specifc ratios and fall back to 16:9 if no such class is added?

Then users could still use the simple embed or add a class for other ratios...

**Comment by lucasdidthis** [comment]
I've noticed, that you're able to choose the size of the embeded video with the classes "wp-embed-aspect-x-y" and "wp-has-aspect-ratio", but it only affects the size of the div element, the embed itself (the preview as well as the iframe) does not show up in the right size. :-/

**Comment by lucasdidthis** [comment]
I'm not getting the JavaScript 100%, but isn't it possible to do something like this

`var ratio = .5625;
if( ELEMENT.classList.contains(".wp-has-embed-ratio") ){
    var classes = ELEMENT.classList;
    var ratio_class = str.substring(
        classes.lastIndexOf("wp-embed-aspect-") + 1, 
        classes.lastIndexOf(" ")
    );
    var split_array = mystring.split("-");
    var x = newarray[0];
    var y = newarray[1]; 
    ratio = Number(y) / Number(x);
}`

to get the ratio from the class of the video if the class "wp-has-embed-ratio" exists and the ratio which used now as a fallback otherwise? Then use the "ratio" variable instead of the fixed number for the calculation of 

`r=Math.round(.5625*n)`

Or am I completely of track here?

**Comment by kevinweber** [comment]
That sounds reasonable to me. I'd have to look more into this, though. Right now, I'm slammed with other opportunities and don't want to prioritize working on this plugin.

If you can it working, you can make a pull request to this project and I'll happily review your changes, provide feedback and merge it.

**Comment by lucasdidthis** [comment]
I did implement it and pushed it to my own fork of the plugin: [https://github.com/lucasdidthis/lazy-load-for-videos/commits/master](https://github.com/lucasdidthis/lazy-load-for-videos/commits/master). I did not minify the Javascript for you to easier review the changes. Propably not the most elegant solution, but it does work on my wordpress blog this way.

**Comment by lucasdidthis** [comment]
I do notice, that there's a little error when calculating for a 21:9 video. The iframe seems to be a few pixels smaller (in height) than the embed-element it's located in. It does not show on the preview-image, but it becomes visible, when the video is loaded (and the iframe has a black background). It does not affect 4:3 or 16:9 videos. 

It does NOT work without the "wp-has-aspect-ratio" class, got to fix that.

Plus the vimeo preview-images are in poor quality. That's another ToDo. I'll keep you updated on my progress.

**Comment by kevinweber** [comment]
Awesome, sounds good.
Once you got things working, it would be nice (though not 100% necessary)
if you can also implement Jest tests for your changes.

Once you're ready, please make a pull request from your fork to the
original repository, link from its description to this issue (#22) and
mention the name of the theme you used for testing this change.

I'll review everything in about 2-3 weeks.

**Comment by kevinweber** [comment]
@lucasdidthis I just looked at your changes and realized something very important: You've been modifying the wrong files. In your branch, you added three new files into the root of the project. Don't ever manually touch the JS files in the assets folder and don't add a new file (unless you know exactly what you're doing). Instead, edit [lazyloadVimeo.js](https://github.com/lucasdidthis/lazy-load-for-videos/blob/master/modules/lazyload-vimeo/lazyloadVimeo.js) and [lazyloadYoutube.js](https://github.com/lucasdidthis/lazy-load-for-videos/blob/master/modules/lazyload-youtube/lazyloadYoutube.js) and follow the development steps described in the README:

1. Install the project-specific npm dependencies (run: `npm install`).
1. Afterwards you can run `npm run watch` to automatically compile all JavaScript and SCSS changes whenever you save a file.
1. Ideally, write tests related to your changes. Make sure that all test cases are succeeding (run: `npm run test`).
1. When you're done, run `npm run production`.

You can keep `npm run watch` running while you change the JS files and the running script will automatically update relevant JS files in the asset directory.

This should make development for you easier and it will allow me the see the exact changes you made very easily.

**Comment by lucasdidthis** [comment]
Thanks for the hint. Unfortunately "npm run watch" and "npm run production" cause errors, even though "npm run test" doesn't. :-(

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lazy-load-for-videos@2.1.0 production: `NODE_ENV=production webpack --config ./webpack.config.js -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lazy-load-for-videos@2.1.0 production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by kevinweber** [comment]
@lucasdidthis Is there more error output than just that? Try the suggestions on StackOverflow: https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle.

Tip: You can use "\`\`\`" followed by text and closed with "\`\`\`" to show multi-line code snippets, like so (ignore the `>`):

```
>```
Some text
More text
On a separate line
>```
```

**Comment by lucasdidthis** [comment]
I was able to fix the error. I had to change the "video.js"-file to implement the change though. I cloned a new fork and created a pull request. I hope i did it right this time. Sorry for the inconvenience.

**Comment by kevinweber** [comment]
Hi @lucasdidthis, I've updated how Vimeo thumbnails are getting requested in version 2.7.8. Now the Vimeo-specific request to retrieve the thumbnail should no longer happen. Once you’ve updated to version 2.7.8, please go to the Lazy Load for Videos admin panel and click the “Update Posts” button at the bottom of the page to apply the change to all posts. Then let me know if the issue is resolved :)

**Comment by lucasdidthis** [comment]
Thanks for the fix and the info. Unfortunately I do not run any Wordpress-Site with your plugin at the moment, so I can't check if the issue is resolved. If I do, I'll let you know!
