### ISSUE TITLE
Compatibility problems with Gutenberg Editor

### ISSUE THREAD

**Issue by mtoensing** [kevinweber/lazy-load-for-videos#39]
I use the Gutenberg Editor and it seems that the plugin code is executed but without the JS magic in the Gutenberg block. This overwrites the normal behaviour of the block. 

Expected behaviour: Normal youtube Gutenberg embed or a preview of the final lazy embed.

![Screen Shot 2020-01-21 at 18 21 34](https://user-images.githubusercontent.com/136737/72827481-2a819200-3c7b-11ea-889d-278ea7d49f5c.png)

**Comment by kevinweber** [comment]
Hi @mtoensing, thank you for reporting this issue.
I've been looking into this and will share my observations here:

- The issue can be reproduced in the WP Twenty Twenty Theme by enabling the plugin
- At first I thought the issue could be related to https://github.com/WordPress/gutenberg/issues/8411 and https://github.com/WordPress/gutenberg/issues/18098 because if I disabled the plugin, the Youtube embeds still looked broken

- Turns out that the issue persists even when the plugin is disabled. Fortunately, this doesn't affect your readers: They will see the videos the way they're supposed to be seen when the plugin is disabled.
- I raised this issue to the WordPress team via StackOverflow and will hopefully hear back soon: https://wordpress.stackexchange.com/questions/357183/block-editor-sandbox-iframe-shows-outdated-html
- --> Milestone 1: Ensure that if you disable the plugin, the default block behavior returns.
- Once we passed milestone 1, I can focus on the original issue and make the previews prettier. I don't want to do that before reaching milestone 1 because "making previews pretty" could cause more issues if we later realize we can't fix the milestone 1 issue.

- Next, we have three options:
1) Show a simple video iframe similar to the default one that you would see without this plugin
2) Only show video thumbnails
3) Fully support lazy-loading including video playback

- --> Milestone 2: Implement one of the three options, ideally option 3.

**Comment by mtoensing** [comment]
The most professional answer I have ever read on a GitHub issue. Thank you.

**Comment by flavourmedia** [comment]
I did run into the same problem and without removing and adding filters I could make it work (without using the_content) by getting the url from the block and adding wp_oembed_get to it.

$not_embedded =  $block['attrs']['url'];
$output = str_replace( $not_embedded, wp_oembed_get($not_embedded), $output );

**Comment by kevinweber** [comment]
@mtoensing @flavourmedia Alrighty, I finally got to this and published proper Gutenberg support with version 2.9. Please update and let me know what you think! Now the block previews should match with what your end users will see. Aside from that, I made several changes under the hood, including properly clearing the caches –– I had to answer my own [StackOverflow question](https://wordpress.stackexchange.com/a/373593/46101)…

Looking forward, the improved setup will make it easy to support setting custom thumbnails per video, an often requested feature. (We can implement this feature by extending [EmbedEdit](https://github.com/kevinweber/lazy-load-for-videos/blob/master/src/frontend/editor/EmbedEdit.tsx) and [EmbedEditControls](https://github.com/kevinweber/lazy-load-for-videos/blob/master/src/frontend/editor/EmbedEditControls.tsx) but let's solve that one on another day.)

Please also [give this plugin a five-star review](https://wordpress.org/support/plugin/lazy-load-for-videos/reviews/) if you haven't done so already.

Cheers!

**Comment by mtoensing** [comment]
Looks great! =) Thank you!

**Comment by dwinnbrown** [comment]
Hey @kevinweber great plugin - really helpful! I just wanted to chime in here as found this old issue report but am having the exact same issues described on the latest version of WP. Currently using the Twenty Twenty One theme but have tested on Twenty Twenty and same issue.
<img width="2289" alt="Screenshot 2020-12-23 at 13 18 26" src="https://user-images.githubusercontent.com/12773283/102999673-6115fb80-4521-11eb-980b-f9e6ad67249c.png">

**Comment by kevinweber** [comment]
Thanks @dwinnbrown, I just checked the latest WP version and can confirm that the preview is broken again. I'm guessing that some of the Gutenberg code has changed that I'm reusing for Lazy Load for Videos. I'd have to do some digging into this but I don't want to make time for this right now; this compatibility problem shouldn't affect your end users, only the editing experience. I'm sorry for the inconvenience. Contributions are welcome 🙏

**Comment by mtoensing** [comment]
My suggestion would be that you provide the option to change the layout in Gutenberg but don't bother to reflect these changes graphically. Just show the normal and standard appearance of a YouTube video embed and provide all settings but leave away the real time preview.

**Comment by dwinnbrown** [comment]
@mtoensing That sounds like a good approach for now 👍  @kevinweber could you possibly point me in the direction of any code I might need to remove/comment out to keep the front-end functionality working but disable the lazy load preview in the back-end?

**Comment by kevinweber** [comment]
@dwinnbrown @mtoensing Unfortunately, just showing the WordPress-default appearance of a YouTube video embed isn't easily possible because of how this plugin works. This plugin transforms the URL into a different HTML snippet that WordPress doesn't recognize as a default embed link anymore by the time it loads embeds in the editor. Given how the WordPress APIs and filters now work, it's probably possible to avoid that transform but it'll require quite a few changes… (I first created this plugin when WordPress was still at version _3.x_ and the APIs were much more limited.)

BUT for now I've fixed the issue and made the thumbnail work again. The issue was caused because the WordPress team introduced the new editor API v2 and this plugin wasn't ready for it. Please make sure you’re using at least WordPress v5.6, then download plugin version 2.13.0 and let me know if the issue is fixed.

**Comment by dwinnbrown** [comment]
Thanks Kevin! Much appreciated - all resolved on my end now.
