### ISSUE TITLE
Lazy load for videos disables embed block size e.g. wide width or full width in Gutenberg Editor

### ISSUE THREAD

**Issue by mtoensing** [kevinweber/lazy-load-for-videos#49]
The latest version of this plugin makes the block size button disappear in Gutenberg: 

Without the plugin activated: 
<img width="661" alt="Screen Shot 2020-09-14 at 21 59 03" src="https://user-images.githubusercontent.com/136737/93132363-c8781000-f6d5-11ea-9e13-24ded14022f1.png">

Lazy load is activated and the button for the block size is missing. 
<img width="751" alt="Screen Shot 2020-09-14 at 21 59 24" src="https://user-images.githubusercontent.com/136737/93132397-d88fef80-f6d5-11ea-849c-7b3f0f444ea1.png">

WordPress 5.5.1
Theme: Twenty Nineteen
--

**Comment by mtoensing** [comment]
@kevinweber Any idea how long this will take to fix? Or is this behavior indented?

**Comment by kevinweber** [comment]
Hi @mtoensing, thanks for reporting this! This is an issue and I'm stuck on getting this working properly. I spent time yesterday trying to fix it but haven't found a satisfying solution yet… I pushed my changes to the master branch; feel free to use those files in the meantime but no guarantee that this will make it to an official WordPress release anytime soon: https://github.com/kevinweber/lazy-load-for-videos/tree/e1b42bd7ae9f08ab9e09ef58675adaf6083ae858
The full-width option seems to be working well. Unfortunately, the other alignment options don't. As soon as you choose "Align left", the video doesn't properly resize and it overflows after videos weirdly once you save the post and reload the editor page. The latter issue is what concerns me most and is the reason why I don't want to publish this change yet. (The issues are only related to the editor experience; the final post for the end user looks just fine.)

Contributions are welcome 🙏

**Comment by kevinweber** [comment]
@mtoensing I just published my change as v2.11.2. The full width alignment works fine now, and left/right-aligned videos should look fine for your readers as well. However, the left/right alignment is buggy in the editor and I don't have a fix for it and I don't plan on supporting left/right alignment anytime soon. Those who want to use it will need to live with the editor-flaws. Because the videos should look fine to your readers despite the flaws, this shouldn't be too much of an issue but let me know in case you think otherwise.

**Comment by mtoensing** [comment]
Solution is fine for me. Thank you!
